nameOverride: demo-trip-aggregator

image: bakdata/quick-demo-monitoring-trip-aggregator
imageTag: latest

streams:
  brokers: "quick-kafka:9092"
  schemaRegistryUrl: "http://quick-sr-schema-registry:8081"
  inputTopics:
    - status
  outputTopic: trip
  productive: false

prometheus:
  jmx:
    enabled: false
