directive @topic(
    name: String!,
    keyArgument: String,
    keyField: String
) on FIELD_DEFINITION

directive @rest(
    url: String!
    pathParameter: [String!]
    queryParameter: [String!]
) on FIELD_DEFINITION

scalar Long
