apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-simulator
spec:
  selector:
    matchLabels:
      app: car-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: car-simulator
    spec:
      containers:
        - name: car-simulator
          image: us.gcr.io/d9p-quick/demo/car-simulator:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: car-simulator-secret
          resources:
            limits:
              cpu: "0.3"
              memory: 256Mi
      imagePullSecrets:
        - name: quick-image-secret