apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "profile-store-app.fullname" . }}
  labels:
    {{- include "profile-store-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "profile-store-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "profile-store-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with (index .Values.ingress.hosts 0) }}
          {{- with (index .paths 0) }}
          env:
            - name: DASH_URL_BASE_PATHNAME
              value: {{ .path }}
          {{- end }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gunicorn"]
          args: {{- range $k, $v := .Values.gunicorn }}
            {{ if eq $k "preload" -}}
            {{- if $v -}}
            - {{ printf "--%s" $k }}
            {{- end -}}
            {{- else -}}
            - {{ printf "--%s" $k }}
            - {{ printf `"%v"` $v }}
            {{- end }}
            {{- end }}
            - "--bind"
            - ":8050"
            - "main:guni_run({{- range $k, $v := .Values.app }}{{ $k }}='{{$v}}',{{- end }})"
          ports:
            - name: http
              containerPort: 8050
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
