apiVersion: v1
kind: Service
metadata:
  name: {{ include "profile-store-app.fullname" . }}
  labels:
    {{- include "profile-store-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8050
      protocol: TCP
      name: http
  selector:
    {{- include "profile-store-app.selectorLabels" . | nindent 4 }}
